import type { Metadata } from 'next'
import './globals.css'
import Providers from "./Providers";
import NavbarServer from '@/components/NavnarServer';
import Sidebar from '@/components/Sidebar';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <Sidebar/>
          <NavbarServer />
          {children}
        </Providers>
      </body>
    </html>
  )
}
